export type Post = {
  __typename: "Post",
      id: string,
      type: string,
      likeCount?: number | null,
      title: string,
      content: string,
      timestamp: number,
      contributorId: string,
      correspondingUserId?: string | null,
      owner?: string | null,
      contributor?:  {
        __typename: "User",
        id: string,
        displayId?: string | null,
        name: string,
        profile: string,
        image?: string | null,
        createdAt: string,
        updatedAt: string,
        correspondingPosts?:  {
          __typename: "ModelPostConnection",
          nextToken?: string | null,
        } | null,
        posts?:  {
          __typename: "ModelPostConnection",
          nextToken?: string | null,
        } | null,
        owner?: string | null,
        comments?:  {
          __typename: "ModelCommentConnection",
          nextToken?: string | null,
        } | null,
        likes?:  {
          __typename: "ModelLikeConnection",
          nextToken?: string | null,
        } | null,
        thankCounts?:  {
          __typename: "ModelThankConnection",
          nextToken?: string | null,
        } | null,
        thank?:  {
          __typename: "ModelThankConnection",
          nextToken?: string | null,
        } | null,
      } | null,
      correspondingUser?:  {
        __typename: "User",
        id: string,
        displayId?: string | null,
        name: string,
        profile: string,
        image?: string | null,
        createdAt: string,
        updatedAt: string,
        correspondingPosts?:  {
          __typename: "ModelPostConnection",
          nextToken?: string | null,
        } | null,
        posts?:  {
          __typename: "ModelPostConnection",
          nextToken?: string | null,
        } | null,
        owner?: string | null,
        comments?:  {
          __typename: "ModelCommentConnection",
          nextToken?: string | null,
        } | null,
        likes?:  {
          __typename: "ModelLikeConnection",
          nextToken?: string | null,
        } | null,
        thankCounts?:  {
          __typename: "ModelThankConnection",
          nextToken?: string | null,
        } | null,
        thank?:  {
          __typename: "ModelThankConnection",
          nextToken?: string | null,
        } | null,
      } | null,
      comments?:  {
        __typename: "ModelCommentConnection",
        items?:  Array< {
          __typename: "Comment",
          id: string,
          type: string,
          content: string,
          timestamp: number,
          userId: string,
          postId: string,
          createdAt: string,
          updatedAt: string,
          owner?: string | null,
        } | null > | null,
        nextToken?: string | null,
      } | null,
      likes?:  {
        __typename: "ModelLikeConnection",
        items?:  Array< {
          __typename: "Like",
          id: string,
          userId: string,
          postId: string,
          owner?: string | null,
        } | null > | null,
        nextToken?: string | null,
      } | null,
      Thanks?:  {
        __typename: "ModelThankConnection",
        items?:  Array< {
          __typename: "Thank",
          id: string,
          userId: string,
          postId: string,
          correspondingUserId: string,
          owner?: string | null,
        } | null > | null,
        nextToken?: string | null,
      } | null,
  } | null
